"""
Headless Zerodha login using Playwright (Chromium).
Completes the official Kite Connect OAuth flow via a real headless browser.
No direct POST to internal endpoints. No ToS violation.

Why Playwright:
  The only legal zero-touch login is completing the actual OAuth browser flow.
  Playwright runs a headless Chromium instance that fills the real login page,
  handles the TOTP field, and catches the redirect URL containing request_token.
  Zerodha sees a normal browser session. Their ToS is not violated.

One-time setup:
  pip install playwright
  playwright install chromium

Flow:
  1. Browser navigates to Kite OAuth URL
  2. Fills user_id + password
  3. Fills TOTP (generated by pyotp)
  4. Catches redirect to your app's redirect_url containing request_token
  5. kite.generate_session(request_token) → access_token
  6. Writes access_token to .env
"""

import os
import time
import pyotp
from kiteconnect import KiteConnect
from dotenv import set_key
from playwright.sync_api import sync_playwright, TimeoutError as PWTimeout
from config import (
    KITE_API_KEY, KITE_API_SECRET,
    ZERODHA_USER_ID, ZERODHA_PASSWORD, ZERODHA_TOTP_SECRET,
    KITE_REDIRECT_URL, ENV_FILE
)

# Official Kite Connect OAuth URL
KITE_OAUTH_URL = (
    f"https://kite.zerodha.com/connect/login"
    f"?v=3&api_key={KITE_API_KEY}"
)


class AutoLogin:

    def _validate_env(self):
        missing = [k for k, v in {
            "KITE_API_KEY":        KITE_API_KEY,
            "KITE_API_SECRET":     KITE_API_SECRET,
            "ZERODHA_USER_ID":     ZERODHA_USER_ID,
            "ZERODHA_PASSWORD":    ZERODHA_PASSWORD,
            "ZERODHA_TOTP_SECRET": ZERODHA_TOTP_SECRET,
            "KITE_REDIRECT_URL":   KITE_REDIRECT_URL,
        }.items() if not v]
        if missing:
            raise RuntimeError(f"Missing .env keys: {missing}")

    def _get_fresh_totp(self) -> str:
        """Wait for a TOTP code with >5 seconds remaining validity."""
        totp      = pyotp.TOTP(ZERODHA_TOTP_SECRET)
        remaining = 30 - (int(time.time()) % 30)
        if remaining < 5:
            time.sleep(remaining + 1)
        return totp.now()

    def login(self) -> str:
        """
        Completes Kite OAuth flow via headless Chromium.
        Returns access_token string. Raises RuntimeError on failure.
        """
        self._validate_env()

        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            page    = browser.new_page()

            # 1 — Navigate to Kite OAuth login page
            page.goto(KITE_OAUTH_URL, timeout=30000)

            # 2 — Fill user_id and password
            page.wait_for_selector('input[type="text"]', timeout=15000)
            page.fill('input[type="text"]', ZERODHA_USER_ID)
            page.fill('input[type="password"]', ZERODHA_PASSWORD)
            page.click('button[type="submit"]')

            # 3 — Wait for TOTP field and fill it
            try:
                page.wait_for_selector(
                    'input[label="External TOTP"],'
                    'input[placeholder="TOTP"],'
                    'input[type="number"]',
                    timeout=15000
                )
            except PWTimeout:
                # Some accounts show security pin field instead
                raise RuntimeError(
                    "TOTP field not found. Check if account uses PIN instead. "
                    "If so, use PIN in ZERODHA_TOTP_SECRET and adjust selector."
                )

            # Capture all requests to steal the redirect URL before Chrome
            # replaces it with chrome-error://chromewebdata/
            captured_urls = []
            page.on("request", lambda req: captured_urls.append(req.url) if "request_token=" in req.url else None)

            page.fill(
                'input[label="External TOTP"],'
                'input[placeholder="TOTP"],'
                'input[type="number"]',
                self._get_fresh_totp()
            )
            try:
                page.click('button[type="submit"]', timeout=3000)
            except Exception:
                pass

            # 4 — Wait for the intercepted request containing request_token
            for _ in range(200):
                if captured_urls:
                    break
                page.wait_for_timeout(100)

            if not captured_urls:
                err = page.query_selector('.error-message, .flash-error')
                err_text = err.inner_text() if err else "unknown"
                raise RuntimeError(
                    f"Login redirect not received. Page error: {err_text}"
                )

            redirect_url = captured_urls[0]
            browser.close()

        # 5 — Extract request_token from redirect URL
        if "request_token=" not in redirect_url:
            raise RuntimeError(
                f"request_token not in redirect URL: {redirect_url[:200]}"
            )
        request_token = redirect_url.split("request_token=")[1].split("&")[0]

        # 6 — Exchange for access_token
        kite         = KiteConnect(api_key=KITE_API_KEY)
        sess         = kite.generate_session(request_token,
                                              api_secret=KITE_API_SECRET)
        access_token = sess["access_token"]

        # 7 — Persist to .env and current process
        set_key(ENV_FILE, "KITE_ACCESS_TOKEN", access_token)
        os.environ["KITE_ACCESS_TOKEN"] = access_token

        return access_token

    def run(self, alert_fn=None) -> bool:
        """Called by scheduler at 8:30 AM."""
        try:
            token = self.login()
            msg   = (f"✅ *AUTO LOGIN SUCCESS*\n"
                     f"Token: `{token[:10]}...`\n"
                     f"Engine armed for 9:30 AM.\n"
                     f"Universe: Nifty 500 | v14")
            if alert_fn:
                alert_fn(msg)
            print(f"[AutoLogin] Success — {token[:10]}...")
            return True
        except Exception as e:
            msg = (f"🚨 *AUTO LOGIN FAILED*\n"
                   f"`{str(e)}`\n"
                   f"Engine will NOT trade today.\n"
                   f"Check credentials immediately.")
            if alert_fn:
                alert_fn(msg)
            print(f"[AutoLogin] FAILED: {e}")
            return False
